### ISSUE TITLE
Error when running UglifyJs

### ISSUE THREAD

**Issue by gillchristian** [franleplant/reform#18]
I'm getting an error from `UglifyJs` when running a production build with [Webpack's UglifyJs plugin.](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/).
```
ERROR in bundle.js from UglifyJs
SyntaxError: Unexpected token punc «,», expected punc «:»
```
It started happening after I added `reform` to the project.

Since it only happens when I try to minify my bundle, I wasn't able to find out where the error is.

This is how I was able to solve the problem:

```js
{
  test: /\.jsx?$/,
  exclude: /node_modules(?!\/@franleplant\/reform)/,
  loader: 'babel-loader'
},
```
EDIT: add relevant `webpack.config.js` snippet.

**Comment by franleplant** [comment]
Got it! Will take a look asap

**Comment by franleplant** [comment]
@gillchristian could you test that the fixes in this branch fix your problem? https://github.com/franleplant/reform/pull/19

**Comment by gillchristian** [comment]
Yes it did! :sunglasses:

**Comment by franleplant** [comment]
ok, releasing new version

**Comment by franleplant** [comment]
Done!
 
```
$ npm publish
+ @franleplant/reform@5.0.7
```

**Comment by gillchristian** [comment]
Awesome, thanks for the quick fix!
