### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by franleplant** [franleplant/reform#3]
This issue is created so we can receive feedback from our users. Anything related to docs should be commented here.

Important points:
- API missing docs
- Missing common uses and patterns
- Something is not understood and could be clarified

Thanks!

Summary of TODOs:
- [ ] Format examples in a homogeneous way (they should be link-able and easy to spot and differentiate with API definitions)
- [ ] Prepend section specific keywords with `keyword` to be super clear about it
- [ ] Document about overwriting native validators
- [ ] Document ways to clear the form

**Comment by gillchristian** [comment]
From the global `validationRules` example one could assume that passing `<native-validator>: true` would work
```jsx
<input
  type="text"
  name="foo"
  value={...}
  onChange={...}
  data-reform={{
    validationRules: {
      globalCustomValidation: true,
      required: true
    }
  }}
/>
```
The assumed behavior would be that the input` is validated with with `globalCustomValidation` & `required`.

**Comment by franleplant** [comment]
Exactly yes. When Reform ends _parsing_ all validation rules the end result is exactly that. All of them end up in `validationRules`

**Comment by gillchristian** [comment]
But the user should not add the native validation rules in `data-reform.validationRules`, instead it should be added in the normal way as a prop of the `<input>` right?

**Comment by franleplant** [comment]
Yes, that's the proffered way, we could give it a bit of a thought and maybe prevent it from happening altogether, or warn the user. But right now I don't think it's a big thing

**Comment by gillchristian** [comment]
I was just pointing that it could be mentioned in the docs.

**Comment by franleplant** [comment]
Im not entirely sure about this, because it's kind of a undocumented back
door for now. I want this API to be as minimal as possible. Probably the
best thing to do is just warn if this happens.

**Comment by franleplant** [comment]
@gillchristian I was looking into the code and it turns out that users cannot directly add native rules to the `validationRules` object. So this will throw and error:

```javascript
validationRules: {
  required: whatever,
}
```

**Comment by gillchristian** [comment]
Yes, I was trying to say that the docs should mention that, because, 

*and I quote my previos comment:*

> From the [Global Validators]
(https://github.com/franleplant/reform#global-validators) example one could assume that passing `<native-validator>: true` would work
```jsx
<input
  type="text"
  name="foo"
  value={...}
  onChange={...}
  data-reform={{
    validationRules: {
      globalCustomValidation: true, {/* this is valid, just means the globalCustomValidation is applied */}
      required: true {/* this is invalid, throws */}
    }
  }}
/>
```

**Comment by franleplant** [comment]
Full circle! You are super right :smile:
