### ISSUE TITLE
Calculate number of weeks for `week.js`

### ISSUE THREAD

**Issue by franleplant** [franleplant/reform#8]
The file needed to change is here: src/officialValidators/week.js  

There's a nice algorithm and description here https://en.wikipedia.org/wiki/ISO_week_date#Weeks_per_year

This is a good place for first time contributors because it's a very contained change.

**Comment by babruix** [comment]
Would appreciate if you can add hacktoberfest label to this issue.

**Comment by franleplant** [comment]
Done!

**Comment by babruix** [comment]
Thanks! 
Let me know if you need help with any of "cosmetic changes" here or help with some other issues, as I have some time this month to spend on "hacktoberfest" initiative.

**Comment by franleplant** [comment]
Of course @babruix thanks a lot for your help. This a very young library and Im being super cautious about over-selling it and over-publishing it but I will definitely have you in mind.

Please be sure to finish the little tweaks I requested on the PR so we can merge it right away!
I need to find a way to mention you somehow in the Change log or something alike (which we don't have currently).

Thanks a lot!

**Comment by babruix** [comment]
Tweaks were included in PR https://github.com/franleplant/reform/pull/12/files
Maybe I have missed something?

**Comment by franleplant** [comment]
Yeap, I made new comments

**Comment by franleplant** [comment]
Fixed!
